# Generated by Django 3.1.3 on 2020-11-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionOfCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sleepDuration', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
