# Generated by Django 3.1.3 on 2020-11-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionOfCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bmi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sleepDuration', models.IntegerField(default=0)),
                ('waterIntake', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('calories', models.IntegerField(default=0)),
                ('gender', models.CharField(default='Female', max_length=7)),
                ('age', models.IntegerField(default=19)),
            ],
        ),
    ]
