# Generated by Django 3.1.3 on 2020-11-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionofcustomer',
            name='waterIntake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionofcustomer',
            name='bmi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='nutritionofcustomer',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='nutritionofcustomer',
            name='sleepDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritionofcustomer',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
