# Generated by Django 3.1.3 on 2020-11-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20201112_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionofcustomer',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
