# Generated by Django 3.1.3 on 2020-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_nutritionofcustomer_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionofcustomer',
            name='age',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='nutritionofcustomer',
            name='gender',
            field=models.CharField(default='Female', max_length=7),
        ),
    ]
