# Generated by Django 3.1.4 on 2020-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(default=532, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_profile_pic',
            field=models.ImageField(blank=True, default='img.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='fitnesscenter',
            name='fitnesscenter_profile_pic',
            field=models.ImageField(blank=True, default='img.png', upload_to='profile_pics'),
        ),
    ]
