# Generated by Django 3.1.3 on 2020-11-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        ('fitbuddy', '0002_auto_20201112_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutritionofcustomer'),
        ),
    ]
