# Generated by Django 3.1.2 on 2020-10-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0006_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='program_pics'),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('WL', 'Weightloss'), ('WG', 'WeightGain'), ('AB', 'BodyBuilding'), ('RG', 'Regular'), ('DC', 'Dance'), ('YG', 'Yoga')], default='RG', max_length=2),
        ),
    ]
