# Generated by Django 3.1.2 on 2020-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0007_auto_20201031_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
