# Generated by Django 3.1.2 on 2020-11-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0008_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('Weight Loss', 'Weightloss'), ('Weight Gain', 'WeightGain'), ('Body Building', 'BodyBuilding'), ('Regular', 'Regular'), ('Dance', 'Dance'), ('Yoga', 'Yoga')], default='Regular', max_length=30),
        ),
    ]
