# Generated by Django 3.1.2 on 2020-11-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0009_auto_20201102_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('WeightLoss', 'Weightloss'), ('WeightGain', 'WeightGain'), ('BodyBuilding', 'BodyBuilding'), ('Regular', 'Regular'), ('Dance', 'Dance'), ('Yoga', 'Yoga')], default='Regular', max_length=30),
        ),
    ]
