# Generated by Django 3.1.2 on 2020-11-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0010_auto_20201102_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('Weight Loss', 'Weightloss'), ('Weight Gain', 'WeightGain'), ('Body Building', 'BodyBuilding'), ('Regular', 'Regular'), ('Dance', 'Dance'), ('Yoga', 'Yoga'), ('Physiotherapy', 'Physiotherapy'), ('Massage Therapy', 'MassageTherapy')], default='Regular', max_length=50),
        ),
    ]
