# Generated by Django 3.1.3 on 2020-11-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0011_auto_20201102_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenter',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
