# Generated by Django 3.1.3 on 2020-11-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0019_auto_20201104_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesscenter',
            name='email',
        ),
    ]
