# Generated by Django 3.1.2 on 2020-11-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0019_auto_20201112_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Gym Trainer', 'GymTrainer'), ('Gym Instructor', 'GymInstructor'), ('Personal Trainer', 'PersonalTrainer'), ('Front desk staff', 'FrontDeskStaff'), ('Sales Manager', 'SalesManager'), ('Fitness Nutritionist', 'Nutritionist'), ('Other', 'Other')], default='Other', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('qualifications', models.TextField()),
                ('responsibilities', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=30)),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('slug', models.SlugField(unique=True)),
                ('fprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitbuddy.program')),
            ],
        ),
    ]
