# Generated by Django 3.1.3 on 2020-11-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0020_remove_fitnesscenter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesscenter',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
    ]
