# Generated by Django 3.1.3 on 2020-11-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0021_fitnesscenter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesscenter',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
