# Generated by Django 3.0.5 on 2020-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbuddy', '0023_auto_20201116_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.IntegerField(),
        ),
    ]
