# Generated by Django 3.1.3 on 2020-11-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussionForum', '0002_auto_20201117_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
