# Generated by Django 3.1.2 on 2020-11-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_fitnessproduct_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessproduct',
            name='contact',
        ),
    ]
