# Generated by Django 3.1.2 on 2020-11-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_remove_fitnessproduct_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessproduct',
            name='slug',
        ),
    ]
