# Generated by Django 3.1.2 on 2020-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_remove_fitnessproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessproduct',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
